// This file is generated by npm run build:icons

export type IconName =
	| "calendar"
	| "check"
	| "chevron"
	| "close"
	| "eyeClosed"
	| "eyeOpened"
	| "logout"
	| "minus"
	| "plus"
	| "question"
	| "thumbsDown"
	| "thumbsUp"
	| "upload"
	| "user";
